### ISSUE TITLE
HTTP可以使用UDP吗？

### ISSUE THREAD

**Issue by Code-Fight** [wolverinn/Waking-Up#1]
感谢大佬分享。

这个问题没有答案。
链接如下：

https://github.com/wolverinn/Waking-Up/blob/master/Computer%20Network.md#http%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8udp%E5%90%97

**Comment by Code-Fight** [comment]
还有一个


https://github.com/wolverinn/Waking-Up/blob/master/Computer%20Network.md#https%E8%BF%9E%E6%8E%A5%E7%9A%84%E6%97%B6%E5%80%99%E6%80%8E%E4%B9%88%E7%A1%AE%E5%AE%9A%E6%94%B6%E5%88%B0%E7%9A%84%E5%8C%85%E6%98%AF%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8F%91%E6%9D%A5%E7%9A%84%E4%B8%AD%E9%97%B4%E4%BA%BA%E6%94%BB%E5%87%BB

**Comment by wolverinn** [comment]
我还不知道一个比较好的答案。。。这两道题是来源于我自己的面试，所以把它加进去了，个人觉得如果单看题的话，可能问题本身也没有描述得很清楚

**Comment by Code-Fight** [comment]
谢谢
