### ISSUE TITLE
计算机网络-“HTTPS连接过程”

### ISSUE THREAD

**Issue by jingshanccc** [wolverinn/Waking-Up#13]
第四点中，“使用Hash算法对握手消息进行摘要计算，并对摘要使用之前产生的密钥加密（对称算法）；将加密后的随机密钥和摘要一起发送给服务器”，需要对摘要加密吗？

**Comment by wolverinn** [comment]
有参考吗，给个链接看下？

**Comment by jingshanccc** [comment]
之前不理解为什么对摘要加密，现在知道了😂
