### ISSUE TITLE
HTTP可以使用UDP, HTTP3.0 正是用的UDP 

### ISSUE THREAD

**Issue by PlexPt** [wolverinn/Waking-Up#37]
原文

> HTTP可以使用UDP吗？
> HTTP不可以使用UDP，HTTP需要基于可靠的传输协议，而UDP不可靠

 
https://zh.wikipedia.org/wiki/HTTP/3

HTTP/3 是即将到来的第三个主要版本的HTTP协议，使用于万维网。与其前任HTTP/1.1和HTTP/2不同，在HTTP/3中，将弃用TCP协议，改为使用基于UDP协议的QUIC协议实现。[1]

此变化主要为了解决HTTP/2中存在的队头阻塞问题。由于HTTP/2在单个TCP连接上使用了多路复用，受到TCP拥塞控制的影响，少量的丢包就可能导致整个TCP连接上的所有流被阻塞。

QUIC（快速UDP网络连接）是一种实验性的网络传输协议，由Google开发，该协议旨在使网页传输更快。在2018年10月28日的邮件列表讨论中，互联网工程任务组（IETF） HTTP和QUIC工作组主席Mark Nottingham提出了将HTTP-over-QUIC更名为HTTP/3的正式请求，以“明确地将其标识为HTTP语义的另一个绑定……使人们理解它与QUIC的不同”，并在最终确定并发布草案后，将QUIC工作组继承到HTTP工作组。[2] 在随后的几天讨论中，Mark Nottingham的提议得到了IETF成员的接受，他们在2018年11月给出了官方批准，认可HTTP-over-QUIC成为HTTP/3。[3]

2019年9月，HTTP/3支持已添加到Cloudflare和Google Chrome（Canary build）。Firefox Nightly将在2019年秋季之后添加支持。[4]

**Comment by wolverinn** [comment]
谢谢
