### ISSUE TITLE
管道是不是应为单工（Simplex）而非半双工？

### ISSUE THREAD

**Issue by dontpanic92** [wolverinn/Waking-Up#40]
> In computer science, an anonymous pipe is a simplex FIFO communication channel that may be used for one-way interprocess communication (IPC).

Ref: https://en.wikipedia.org/wiki/Anonymous_pipe

**Comment by dontpanic92** [comment]
> 管道是半双工的，数据只能向一个方向流动

从后半句的描述来看也是单工，似乎是笔误？

**Comment by zhsama** [comment]
> > 管道是半双工的，数据只能向一个方向流动
> 
> 从后半句的描述来看也是单工，似乎是笔误？

单工指只有一方能发送信息，另一方只能接收。

半双工数据可以双向流动，但同一时间只能向一个方向。在父子进程进行管道通信的时候，父进程先pipe创建管道之后，子进程也会得到同一个管道的读写文件描述符（fork），从而实现了父子两个进程使用一个管道可以完成半双工通信。

更详细的内容可以参考《UNIX环境高级编程》。

![image](https://user-images.githubusercontent.com/33454514/122715022-db3df780-d29a-11eb-91cd-d67a8198bf09.png)

**Comment by dontpanic92** [comment]
单工/双工是信道本身的属性，上面的图里也能看出这个 pipe 依然是右进左出，按照我的理解 pipe 的属性应该与如何使用它无关。我去查了 APUE，确实明确写明 Unix Pipe 是 half-duplex，但按照描述我仍然觉得这应该是个单工信道，有点疑惑。搜了一下似乎也没有这方面进一步的讨论。

不过面试也不会这么抠字眼，我就先把 PR 关了，这个 Issue 再多开一会
