### ISSUE TITLE
可以增加一下协程coroutine

### ISSUE THREAD

**Issue by XifeiNi** [wolverinn/Waking-Up#9]
协程是一种用户态的轻量级线程，协程的调度完全由用户控制。协程拥有自己的寄存器上下文和栈。协程调度切换时，将寄存器上下文和栈保存到其他地方，在切回来的时候，恢复先前保存的寄存器上下文和栈，直接操作栈则基本没有内核切换的开销，可以不加锁的访问全局变量，所以上下文的切换非常快。

**协程多与线程进行比较**

1) 一个线程可以多个协程，一个进程也可以单独拥有多个协程，这样python中则能使用多核CPU。

2) 线程进程都是同步机制，而协程则是异步

3) 协程能保留上一次调用时的状态，每次过程重入时，就相当于进入上一次调用的状态

**Comment by XifeiNi** [comment]
因为最近很多面经都提到了。

**Comment by wolverinn** [comment]
谢谢，赞一个
